host: https://egov-micro-dev.egovernments.org/
stateCode: pb
cityCode: amritsar
# Super User credentials for login(need to create user manually)
superUser:
  userName: amr001
  password: 12345678
  type: EMPLOYEE