name: Maven CI/CD

on:
  push:
    branches: [hcm_base_branch]
  pull_request:
    branches: [hcm_base_branch]
  schedule:
    - cron: "0 5 * * *"

jobs:
  test_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v3
        with:
          ref: hcm_base_branch

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore

      - name: Build and test project with Maven
        run: |
          cd /home/runner/work/test-automation/test-automation/api-automation
          ls -lrta
          mvn clean install "-Dtags=@hcm" "-DconfigPath=/home/runner/work/test-automation/test-automation/api-automation/health-qa.yaml"
          ls -R /home/runner/work/test-automation/test-automation/api-automation/target/ext*/eGov*

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            /home/runner/work/test-automation/test-automation/api-automation/target/ext*/eGov*.html
          retention-days: 365
